version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "--workers", "3", "book.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
